import manifest from "./media-manifest.json";

/**
 * Project media, generated by `scripts/optimize-media.py` from the originals kept in
 * /Users/ilanziv/Code/adinegev-media-archives/project-media-originals/ (not in the repo).
 */
export interface MediaFile {
  filename: string;
  stem: string;
  date: string;
  time: string;
  sequence: number;
  type: "image" | "video";
  width: number;
  height: number;
  /** ~560px WebP thumbnail (poster frame for videos) */
  thumb: string;
  /** ~1600px WebP for the lightbox (images) or poster (videos) */
  large: string;
  /** H.264 MP4 (videos only) */
  video?: string;
}

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || "";
export const mediaUrl = (p: string) => `${BASE_PATH}/media/${p}`;

type Raw = (typeof manifest)[number];

function toMedia(r: Raw): MediaFile {
  const isVideo = r.type === "video";
  return {
    filename: r.filename,
    stem: r.stem,
    date: r.date,
    time: r.time,
    sequence: r.sequence,
    type: isVideo ? "video" : "image",
    width: r.width,
    height: r.height,
    thumb: mediaUrl(`thumb/${r.stem}.webp`),
    large: mediaUrl(isVideo ? `poster/${r.stem}.webp` : `large/${r.stem}.webp`),
    video: isVideo ? mediaUrl(`video/${r.stem}.mp4`) : undefined,
  };
}

export const HERO_IMAGE = {
  src: mediaUrl("hero-1400.webp"),
  srcSet: `${mediaUrl("hero-800.webp")} 800w, ${mediaUrl("hero-1400.webp")} 1400w`,
  width: 1400,
  height: 1050,
};

export const TOUR_VIDEO = {
  src: mediaUrl("video/2026-07-06_200751_4.mp4"),
  poster: mediaUrl("poster/2026-07-06_200751_4.webp"),
};

/** Chronological: date → time → sequence → filename */
export function compareMediaChronological(a: MediaFile, b: MediaFile): number {
  return (
    a.date.localeCompare(b.date) ||
    a.time.localeCompare(b.time) ||
    a.sequence - b.sequence ||
    a.filename.localeCompare(b.filename)
  );
}

export function getProjectMedia(): MediaFile[] {
  return (manifest as Raw[]).map(toMedia).sort(compareMediaChronological);
}

/** Planning stage (02): visualizations / plans only */
const PLANNING_FILES = new Set([
  "2026-04-10_100000_1.jpeg",
  "2026-04-10_100001_1.png",
  "2026-04-10_100002_1.jpg",
  "2026-04-10_100003_1.mp4",
]);

const PHASE_RANGES = [
  { phase: "phase-1", startDate: "2026-04-01", endDate: "2026-04-30" },
  { phase: "phase-2", startDate: "2026-05-01", endDate: "2026-05-31" },
  { phase: "phase-3", startDate: "2026-06-01", endDate: "2026-06-30" },
  { phase: "phase-4", startDate: "2026-07-01", endDate: "2026-07-31" },
];

export function getMediaByPhase(): Record<string, MediaFile[]> {
  const phaseMedia: Record<string, MediaFile[]> = {
    "phase-0": [],
    "phase-1": [],
    "phase-2": [],
    "phase-3": [],
    "phase-4": [],
  };
  for (const m of getProjectMedia()) {
    if (PLANNING_FILES.has(m.filename)) {
      phaseMedia["phase-0"].push(m);
      continue;
    }
    const r = PHASE_RANGES.find((p) => m.date >= p.startDate && m.date <= p.endDate);
    if (r) phaseMedia[r.phase].push(m);
  }
  return phaseMedia;
}
